// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJhcsKEzI6YANMbIyLiF75VfnGmqyXONM',
    appId: '1:837391700206:web:b5d6a37a31b3b622b423ff',
    messagingSenderId: '837391700206',
    projectId: 'farmer-app-a7679',
    authDomain: 'farmer-app-a7679.firebaseapp.com',
    storageBucket: 'farmer-app-a7679.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2H-BIOB4OPhBDpXJldEXZw77KnaJyS8',
    appId: '1:837391700206:android:00f3a3ce287e3268b423ff',
    messagingSenderId: '837391700206',
    projectId: 'farmer-app-a7679',
    storageBucket: 'farmer-app-a7679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQuO2-X5ZPoIyvgRKWzAZipR56RxbCjdo',
    appId: '1:837391700206:ios:73c752f43613dacdb423ff',
    messagingSenderId: '837391700206',
    projectId: 'farmer-app-a7679',
    storageBucket: 'farmer-app-a7679.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQuO2-X5ZPoIyvgRKWzAZipR56RxbCjdo',
    appId: '1:837391700206:ios:73c752f43613dacdb423ff',
    messagingSenderId: '837391700206',
    projectId: 'farmer-app-a7679',
    storageBucket: 'farmer-app-a7679.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJhcsKEzI6YANMbIyLiF75VfnGmqyXONM',
    appId: '1:837391700206:web:49ad88eb3cf2c1fab423ff',
    messagingSenderId: '837391700206',
    projectId: 'farmer-app-a7679',
    authDomain: 'farmer-app-a7679.firebaseapp.com',
    storageBucket: 'farmer-app-a7679.firebasestorage.app',
  );
}
